# Section 1: Array Creation & Reshaping (Q1–Q4)

1.Matrix Creation ⭐⭐

Create the following matrix without typing every element manually.

[[ 1  2  3  4]

 [ 5  6  7  8]
 
 [ 9 10 11 12]]

In [2]:
import numpy as np

a=np.arange(1,13)
b=a.reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2.Checkerboard Pattern ⭐⭐⭐

Create an 8×8 checkerboard.

Output

0 1 0 1 0 1 0 1

1 0 1 0 1 0 1 0

0 1 0 1 0 1 0 1

... 

In [14]:
a=np.ones((8,8),dtype='int8')
a[0,0:8:2]=0
a[2,0:8:2]=0
a[4,0:8:2]=0
a[6,0:8:2]=0
a[1,1:8:2]=0
a[3,1:8:2]=0
a[5,1:8:2]=0
a[7,1:8:2]=0
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Q3. Border Matrix ⭐⭐⭐

Create a 10×10 matrix

Border = 1
Inside = 0

Output

1111111111

1000000001

1000000001

...

1111111111

In [18]:
mat=np.zeros((10,10),dtype='int8')
mat[0,:]=1
mat[-1,:]=1
mat[:,0]=1
mat[:,-1]=1
print(mat)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


Q4. Reshape Challenge ⭐⭐⭐

Given

a = np.arange(1, 25)

Convert it into

Shape

(2,3,4)

Then flatten it back into a 1D array.

In [21]:
a=np.arange(1,25)
a=a.reshape((2,3,4))
print(a)
a=a.flatten()
print(a)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


# Section 2: Indexing & Boolean Masking (Q5–Q8)

Q5. Even Numbers ⭐⭐⭐

Given

a = np.arange(1,101)

Extract only the even numbers.

Restrictions

Boolean masking only.

In [25]:
a = np.arange(1,101)
a=a[a%2==0]
print(a)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


Q6. Multiples ⭐⭐⭐
Replace every number divisible by 5 with -1.

In [26]:
a = np.arange(1,101)
a[a%5==0]=-1
print(a)

[ 1  2  3  4 -1  6  7  8  9 -1 11 12 13 14 -1 16 17 18 19 -1 21 22 23 24
 -1 26 27 28 29 -1 31 32 33 34 -1 36 37 38 39 -1 41 42 43 44 -1 46 47 48
 49 -1 51 52 53 54 -1 56 57 58 59 -1 61 62 63 64 -1 66 67 68 69 -1 71 72
 73 74 -1 76 77 78 79 -1 81 82 83 84 -1 86 87 88 89 -1 91 92 93 94 -1 96
 97 98 99 -1]


Q7. Row Filtering ⭐⭐⭐

Given

students = np.array([
[101,78],

[102,35],

[103,91],

[104,40],

[105,88]
])

Keep only students scoring greater than or equal to 50.

In [27]:
students = np.array([
[101,78],
[102,35],
[103,91],
[104,40],
[105,88]
])
students=students[students[:,1]>50]
print(students)

[[101  78]
 [103  91]
 [105  88]]


Q8. Conditional Replacement ⭐⭐⭐⭐

Given

a = np.array([2,-3,5,-1,8,-6])

Replace negative values with their absolute value.

In [28]:
a = np.array([2,-3,5,-1,8,-6])
b = np.where(a<0,a*(-1),a)
print(b)

[2 3 5 1 8 6]


# Section 3: Broadcasting & Vectorization (Q9–Q12)

Q9. Matrix Addition ⭐⭐⭐

In [30]:
A = np.array([
[1,2,3],
[4,5,6],
[7,8,9]
])

b = np.array([10,20,30])
print(A+b)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


Q10. Normalize Data ⭐⭐⭐⭐

In [38]:
X = np.array([
[10,20],
[30,40],
[50,60]
])

mean=np.mean(X,axis=0)
var=np.var(X,axis=0)
X_norm=(X-mean)/var
print(X_norm)


[[-0.075 -0.075]
 [ 0.     0.   ]
 [ 0.075  0.075]]


Distance Calculation ⭐⭐⭐⭐

Given

points = np.array([
[1,2],
[4,6],
[7,8]
])

Find the Euclidean distance of every point from the origin (0,0).

In [41]:
points = np.array([
[1,2],
[4,6],
[7,8]
])

distance=np.sqrt(np.sum(points**2,axis=1))
print(distance)

[ 2.23606798  7.21110255 10.63014581]


Image Brightness ⭐⭐⭐⭐

Given

image = np.random.randint(0,256,(5,5))

Increase brightness by 50

Values must not exceed 255.

In [46]:

image = np.random.randint(0, 256, (5,5))
bright_image = np.where(image<=200, image+50 , image)

print("Original Image:\n", image)
print("\nBrightened Image:\n", bright_image)


Original Image:
 [[ 19 116  85 153 183]
 [  9 117  69 232 183]
 [208 251  58 156  62]
 [255  60  27 140 103]
 [ 17   1 199 254 245]]

Brightened Image:
 [[ 69 166 135 203 233]
 [ 59 167 119 232 233]
 [208 251 108 206 112]
 [255 110  77 190 153]
 [ 67  51 249 254 245]]


# Section 4: Mathematical Operations & Aggregation (Q13–Q16)

Q13. Highest Scorer ⭐⭐⭐

Given

marks = np.array([67,89,92,55,78])

Find

Maximum mark
Index of topper

In [49]:
marks = np.array([67,89,92,55,78])
print(np.max(marks))
print(np.argmax(marks))

92
2


Q14. Statistics ⭐⭐⭐⭐

Given

data = np.array([10,15,20,25,30,35,40])

Calculate

Mean
Median
Standard deviation
Variance

In [51]:
data = np.array([10,15,20,25,30,35,40])
print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.var(data))

25.0
25.0
10.0
100.0


Q15. Matrix Multiplication ⭐⭐⭐⭐

Multiply

In [55]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

C=np.matmul(A,B)
print(C)

[[19 22]
 [43 50]]


Q16. Percentiles ⭐⭐⭐⭐

In [56]:
scores = np.array([45,56,78,90,65,82,74,60])
print(np.percentile(scores,25))
print(np.percentile(scores,50))
print(np.percentile(scores,75))

59.0
69.5
79.0


# Section 5: Random Module (Q17–Q18)

Q17. Random Dataset ⭐⭐⭐⭐

Generate a dataset

Shape (100,5)
Random integers
Between 1 and 100
Use seed 42

In [59]:
rng = np.random.default_rng(42)
rng.integers(1,100,(100,5))

18.Sampling ⭐⭐⭐⭐

Generate

10 unique random numbers
Between 1 and 100
No duplicates

In [68]:
print(np.random.choice(np.arange(1,101),size=10,replace=False))

[56 37 61 73  1 76 44 65 63 15]


# Section 6: Hard AI/ML Problems (Q19–Q20)

Q19. Min-Max Scaling ⭐⭐⭐⭐⭐

In [71]:
X = np.array([
[100,200],
[150,300],
[120,250]
])

mini=np.min(X,axis=0)
maxi=np.max(X,axis=0)

X_scaled=(X-mini)/(maxi-mini)
print(X_scaled)

[[0.  0. ]
 [1.  1. ]
 [0.4 0.5]]


Q20. Outlier Detection

In [80]:
data = np.array([
12,15,18,20,22,24,25,27,
29,30,35,120
])

Q1=np.percentile(data,25)
Q3=np.percentile(data,75)
IQR=Q3-Q1
print(IQR)
lower=Q1-1.5*(IQR)
upper=Q3+1.5*(IQR)
outliers=data[(data<lower) | (data>upper)]
print(outliers)


9.75
[120]
