# Numpy Bascis

In [ ]:
import numpy as np
print(np.__version__)

In [ ]:
# ndarray = N-dimensional array.
# Stores only one dtype.
# Has attributes like shape, ndim, size, and dtype.
# Memory efficient compared to Python lists.
# Supports broadcasting and vectorization.
# Operations are implemented in optimized C code.
# Fixed-size container.
# Most ML datasets become NumPy arrays before training.

In [129]:
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [130]:
# shape == Returns the size of each dimension of an array.

arr1=np.array([[1,2,3,4],[2,3,6,8]])
print(arr1.shape)

(2, 4)


In [131]:
# ndim	Returns the number of axes (dimensions) in an array.
# 1D Array	One axis → ndim = 1
# 2D Array	Rows & columns → ndim = 2
# 3D Array	Depth, rows & columns → ndim = 3
arr2=np.array([[1,2,3],[1,5,7],[3,6,9]])
print(arr2.ndim)

image=np.zeros((224,224,3))
print(image.ndim)

2
3


In [132]:
# size==Returns the total number of elements in an array.
print(image.size)

150528


In [133]:
# dtype	Returns the data type of the array.
# dtype=	Specifies the data type during array creation.
# astype()	Converts an array to a new data type.

print(image.dtype)
arr=np.array([1,2,3],dtype=np.float32)
print(arr.dtype)
arr=arr.astype(np.float64)
print(arr.dtype)

float64
float32
float64


In [134]:
# Memory Layout	Defines how multi-dimensional arrays are stored in memory.
# C-order	Row-major order (rows stored first). NumPy default.
# Fortran-order	Column-major order (columns stored first).
# Performance	Accessing data in its storage order is faster due to cache locality.
# Importance	Useful when optimizing performance or interfacing with libraries like BLAS/LAPACK.

arr_c = np.array([[1, 2],
                  [3, 4]], order='C')

arr_f = np.array([[1, 2],
                  [3, 4]], order='F')

print(arr_c)
print(arr_f)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [135]:
# strides Number of bytes NumPy skips in memory to move to the next element along each axis.
print(arr_c.strides)
# 16 indicates the row
# 8 indicates the coloumn

(16, 8)


# accessing/changing specific elements ,rows ,columns etc.

In [136]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [137]:
#To get a specific element ==[row index,column index]
print(a[1,5])
print(a[1,-2])

13
13


In [138]:
#To get a specific Row
a[0 , :]

array([1, 2, 3, 4, 5, 6, 7])

In [139]:
#To get a specific Column
a[: ,2]

array([ 3, 10])

In [140]:
# Getting Little more fance[start index:stop index: step size]
print(a[0, 1:6:2])
print(a[0, 1:-1:2])

[2 4 6]
[2 4 6]


In [141]:
#To change specific element
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [142]:
#To change an entire column
a[:,2]=55
print(a)

[[ 1  2 55  4  5  6  7]
 [ 8  9 55 11 12 20 14]]


In [143]:
#To change an entire column in sequential way
a[:,2]=[55,56]
print(a)

[[ 1  2 55  4  5  6  7]
 [ 8  9 56 11 12 20 14]]


In [144]:
# 3D example
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [145]:
#To get a specific element(work outside in)
print(b[0,1,2])

6


In [146]:
#fancy works
print(b[:,0,:])#all the zeroth rows
print()
print(b[:,:,0])#all the zeroth columns
print()
print(b[0,:,0])#first's zeroth column

[[1 2 3]
 [7 8 9]]

[[ 1  4]
 [ 7 10]]

[1 4]


In [147]:
#to replace
b[0,0,:]=[11,22,33]
print(b)

[[[11 22 33]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Intializing different arrays

In [148]:
#All 0's Matrix
print(np.zeros(5))
print()
print(np.zeros((2,3)))
print()
print(np.zeros((2,3,3)))

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [149]:
#All 1's Matrix
print(np.ones((5),dtype='int32'))
print()
print(np.ones((2,3)))
print()
print(np.ones((2,3,3)))

[1 1 1 1 1]

[[1. 1. 1.]
 [1. 1. 1.]]

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [150]:
#any other number
np.full((2,2),19)

array([[19, 19],
       [19, 19]])

In [151]:
#any other number[full_like] useful in the situvation where u have to do in other dimension
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [152]:
# empty() Creates an array without initializing values.Creates an array without initializing values.
# Output (Random Garbage)

np.empty((2,2))

array([[4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323]])

In [153]:
# diag() Creates or extracts diagonal elements.
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [154]:
# arange() Creates evenly spaced numbers.
# np.arange(start, stop, step)
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [155]:
#random decimal numbers
np.random.rand(2,4)

array([[0.37223286, 0.93962854, 0.34826432, 0.10883023],
       [0.16523388, 0.73807372, 0.30807279, 0.56119656]])

In [156]:
#to do it in particular shape
np.random.random_sample(a.shape)

array([[0.3207307 , 0.10744084, 0.02557046, 0.79762082, 0.14020633,
        0.32394638, 0.10239292],
       [0.62255269, 0.92748236, 0.79801088, 0.52118007, 0.8721818 ,
        0.54970806, 0.60977292]])

In [157]:
#random integer values==(limit,size=())
np.random.randint(2,7,size=(3,3),dtype='int16')

array([[6, 6, 6],
       [4, 6, 5],
       [6, 5, 5]], dtype=int16)

In [158]:
#Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [159]:
#to repeat arrays
arr=np.array([[1,2,3]])#now its 2D
r1=np.repeat(arr,3,axis=0)
print(r1)
print()
r2=np.repeat(arr,3,axis=1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]

[[1 1 1 2 2 2 3 3 3]]


In [160]:
#Excercise
arr_ex=np.zeros((5,5),dtype='int16')
arr_ex[0,:]=1
arr_ex[-1,:]=1
arr_ex[:,0]=1
arr_ex[:,-1]=1
arr_ex[2,2]=9

print(arr_ex)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [161]:
a=np.array([1,2,3])
b=a.copy()#without this copy() a and b are same whatever changes u make it will affect both
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


# Mathematics

In [162]:
arr=np.array([1,2,3])

In [163]:
arr+2

array([3, 4, 5])

In [164]:
arr*2

array([2, 4, 6])

In [165]:
arr/2

array([0.5, 1. , 1.5])

In [166]:
arr-2

array([-1,  0,  1])

In [167]:
arr**2

array([1, 4, 9])

In [168]:
b=np.array([0,1,0])
print(a+b)

[1 3 3]


# Trignometric Functions

In [215]:
print(np.cos(a))
print()
print(np.sin(a))
print()
print(np.tan(a))
print()
print(np.deg2rad(90))
print(np.rad2deg(np.pi))

[[0.92607439 0.7968627  0.99998046]
 [0.75507647 0.62615802 0.72504478]
 [0.63867598 0.93784578 0.65301447]]

[[0.37734099 0.60416045 0.00625154]
 [0.65563674 0.77969618 0.68870173]
 [0.76947579 0.3470523  0.75734543]]

[[0.40746293 0.75817383 0.00625166]
 [0.86830509 1.24520672 0.94987475]
 [1.2047984  0.37005263 1.15976821]]

1.5707963267948966
180.0


# Linear Algebra

In [171]:
#Matrix Multiplication

a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
print()
print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]

[[6. 6.]
 [6. 6.]]


In [195]:
# Determinant

c=np.identity(3)
print(np.linalg.det(c))

1.0


In [203]:
# TO get Inverse of function
a=np.random.rand(3,3)
if np.linalg.det(a)!=0:
    print(np.linalg.inv(a))

[[-0.05689917 -1.58157282  1.52073957]
 [-1.11020745  0.79180438  0.78368439]
 [ 2.35103887  1.29141859 -2.1700857 ]]


In [204]:
# To get a rank of matrix
a=np.random.rand(3,3)
print(np.linalg.matrix_rank(a))

3


In [206]:
# For eigen values and eigen vectors
A=np.random.rand(3,3)
values, vectors = np.linalg.eig(A)
print(values)
print()
print(vectors)

[ 1.4859523 +0.j -0.22117495+0.j -0.77377994+0.j]

[[-0.4383651 +0.j -0.86414968+0.j  0.45474701+0.j]
 [-0.63782005+0.j  0.47443217+0.j -0.72204456+0.j]
 [-0.63326268+0.j  0.16780778+0.j  0.52139889+0.j]]


In [208]:
# Solve Linear system
# Ax=B

A = np.array([[2,1],
              [1,3]])

B = np.array([8,13])

print(np.linalg.solve(A,B))

[2.2 3.6]


In [211]:
# Norm
# Types
# L1 Norm
# L2 Norm (default)
# Frobenius Norm
# AI/ML Use
# Regularization

A=np.random.rand(3,3)
print(np.linalg.norm(A))

1.3586749866128582


In [212]:
# Sum of Diagonal Elements

A=np.random.rand(3,3)
print(np.trace(A))

0.8827302480415135


# Reshaping

In [173]:
# reshape() Changes the shape of an array.
a = np.arange(1,7)
print(a.reshape(2,3))
print()
print(a.reshape(3,-1))

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


In [174]:
# flatten() Converts a multi-dimensional array into a 1D array.
b=np.array([[1,2],[3,4]])
print(b.flatten())


[1 2 3 4]


In [175]:
# T used to Transpose the Matrix
a = np.array([[1,2,3],
              [4,5,6]])

print(a.T)

[[1 4]
 [2 5]
 [3 6]]


# Broadcasting

In [176]:
# Broadcasting is NumPy's mechanism for performing element-wise operations between arrays of 
# different shapes by automatically expanding the smaller array when possible.

a = np.array([1,2,3])
b = 10 #b treated as [10 10 10]
print(a + b)

[11 12 13]


In [177]:
# Broadcasting Rules
# ✅ They are equal
# ✅ One of them is 1
# ❌ Otherwise → Broadcasting Error

In [178]:
# a=(4,3)
# b=(3,)now its reshaped as (,3)--->(4,3)

In [179]:
# a=(4,3)
# b=(4,1)--->(4,3)

In [180]:
# a=(3,4,2)
# b=(4,2)--->(3,4,2)

In [181]:
# a=(3,4)
# b=(3,2)-->broadcasting error because there is no 1 and its not same shape so it generates error

# NumPy Vectorization

In [182]:
# Why Loops are Slow
# Python loops execute one element at a time.
# Why NumPy is Faster
# ✅ Written in C
# ✅ Optimized memory access
# ✅ SIMD (Single Instruction Multiple Data) support
# ✅ No Python loop overhead
# ✅ Better CPU cache utilization

In [184]:
# Universal Functions
# Universal Functions (ufuncs) are optimized NumPy functions that perform element-wise operations on arrays.

# np.add()
# np.subtract()
# np.multiply()
# np.divide()
# np.power()
# np.mod()

a = np.array([1,2,3])
print(np.multiply(a,2))
print(np.subtract(a,2))


[2 4 6]
[-1  0  1]


In [185]:
# Mathemetics
# np.sqrt()
# np.exp()
# np.log()
# np.sin()
# np.cos()
# np.tan()
# np.abs()

np.sqrt([1,4,9])

array([1., 2., 3.])

In [186]:
# Comparison
# np.maximum()
# np.minimum()
# np.equal()
# np.greater()

np.maximum([1,5,3],[2,2,6])

array([2, 5, 6])

In [190]:
# Element-wise Operations
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(b%a)
print(a**b)


[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[ 4 10 18]
[0 1 0]
[  1  32 729]


In [191]:
# Performance Benchmarking
# Use the time or timeit module to compare performance.

# python loop

import time
import numpy as np

a = np.arange(1_000_000)

start = time.time()

result = []

for x in a:
    result.append(x * 2)

print(time.time() - start)

0.2448253631591797


In [192]:
# Numpy Vectorization
start = time.time()

result = a * 2

print(time.time() - start)

0.03144526481628418


In [194]:
# Better Benchmarking with timeit

import timeit
timeit.timeit("a*2", globals=globals(), number=100)

0.3429962999998679

# Aggregation Functions

In [216]:
# sum
# mean
# median
# std
# var
# min
# max
# argmax
# argmin
# percentile
# quantile

In [237]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(np.sum(a))
print(np.sum(a,axis=1))#row wise sum
print(np.sum(a,axis=0))#column wise sum
print()



45
[ 6 15 24]
[12 15 18]



In [238]:
print(np.mean(a))
print(np.mean(a,axis=1))#row wise mean
print(np.mean(a,axis=0))#column wise mean
print()



5.0
[2. 5. 8.]
[4. 5. 6.]



In [239]:
b = np.array([1,2,3,100])
print(np.median(b))
print()



2.5



In [240]:
print(np.std(a))#standard deviation
print()

print(np.var(a))#varience
print()



2.581988897471611

6.666666666666667



In [241]:
print(np.min(a))
print(np.min(a,axis=1))#row wise 
print(np.min(a,axis=0))#column wise 
print()

print(np.max(a))
print(np.max(a,axis=1))#row wise 
print(np.max(a,axis=0))#column wise 
print()

1
[1 4 7]
[1 2 3]

9
[3 6 9]
[7 8 9]



In [242]:
print(np.argmax(a))#return index of maximum value
print(np.argmax(a,axis=1))#row wise
print(np.argmax(a,axis=0))#column wise
print()

print(np.argmin(a))#return index of minimum value
print(np.argmin(a,axis=1))#row wise
print(np.argmin(a,axis=0))#column wise
print()

8
[2 2 2]
[2 2 2]

0
[0 0 0]
[0 0 0]



In [243]:
a = np.array([1,2,3,4,5])
print(np.percentile(a,50))#Returns the value below which a given percentage of observations falls.
print(np.percentile(a,75))

3.0
4.0


# NumPy Boolean Masking

In [244]:
a = np.array([10,20,30,40,50])
mask = a > 25
print(mask)
print(a[mask])

[False False  True  True  True]
[30 40 50]


In [246]:
# Filtering Rows
marks=np.array([10,20,40,60,70,80,90])
passed=marks[marks>=35]
print(passed)
print()

students = np.array([[1,85],
                     [2,40],
                     [3,95]])
print(students[students[:,1]>=50])

[40 60 70 80 90]

[[ 1 85]
 [ 3 95]]


In [253]:
# Conditional Replacement
a=np.array([-10,20,30,-40,50,60,-70,80,-90])
a[a < 0]=0 #remove negative values
print(a)



[ 0 20 30  0 50 60  0 80  0]


In [255]:
# np.where(condition, value_if_true, value_if_false)

a = np.array([10,20,30,40,-50,-25])
b = np.where(a<0 ,a*(-1), a) #changes the negative to positive
print(b)

[10 20 30 40 50 25]


In [257]:
# Data Selection

a = np.array([5,10,15,20])
print(a[a > 10])
print(a[(a > 10) & (a < 20)]) #AND operation
print(a[(a < 10) | (a > 15)])# OR operation
print(a[~(a > 10)])#NOT operation

[15 20]
[15]
[ 5 20]
[ 5 10]


# NumPy Random Module

In [258]:
# Random Float (0 to 1)
rng = np.random.default_rng()
rng.random()

0.7626168928328788

In [263]:
# Multiple Random Floats
rng.random(5)

array([0.24252144, 0.00399456, 0.86381917, 0.28736216, 0.95482305])

In [265]:
# Random Integer
print(rng.integers(1, 10))

5


In [266]:
# 2D Random Array
rng.random((2,3))

array([[0.79759968, 0.5459582 , 0.70357417],
       [0.44174405, 0.96008006, 0.86202444]])

In [269]:
# Random Seed
# Purpose
# A seed ensures the same sequence of random numbers is generated every time.
rng = np.random.default_rng(42)
print(rng.random(3))

[0.77395605 0.43887844 0.85859792]


In [272]:
# Random Distributions
# Uniform Distribution
rng.uniform(10, 20, 5)

array([18.22761613, 14.43414199, 12.27238722, 15.54584787, 10.63817256])

In [275]:
# Normal (Gaussian) Distribution

# loc → Mean
# scale → Standard deviation
# size → Number of samples

rng.normal(loc=0, scale=1, size=5)

array([ 0.41273261,  0.430821  ,  2.1416476 , -0.40641502, -0.51224273])

In [276]:
# Binomial Distribution
rng.binomial(n=10, p=0.5, size=5)

array([4, 5, 4, 3, 5])

In [277]:
# Choice from Values
rng.choice([10,20,30], size=5)

array([10, 10, 20, 30, 30])

In [278]:
# Shuffling 
# shuffle()
# Shuffles in-place.
# original gets changed
a = np.array([1,2,3,4,5])
rng.shuffle(a)
print(a)

[5 4 1 2 3]


In [281]:
# permutation()
# Returns a shuffled copy.

a = np.array([1,2,3,4,5])
b = rng.permutation(a)
print(b)
print(a)

[1 5 4 2 3]
[1 2 3 4 5]


In [284]:
# Sampling ⭐⭐⭐⭐⭐
# Random Sample Without Replacement
# No duplicates.
rng.choice(10, size=5, replace=False)

array([3, 7, 8, 5, 4])

In [285]:
# Sample With Replacement
# Duplicates allowed.
rng.choice(10, size=5, replace=True)

array([4, 6, 6, 4, 8])

In [286]:
# Reproducibility 
# Reproducibility means getting the same results every time.
# Without seed

rng = np.random.default_rng()
print(rng.random(3))

[0.9315374  0.361792   0.29117433]


In [288]:
# With seed

rng = np.random.default_rng(42)
print(rng.random(3))

[0.77395605 0.43887844 0.85859792]
